### ISSUE TITLE
Compose file is invalid

### ISSUE THREAD

**Issue by PJF16** [stegm/marvell_msu_docker#4]
Hello!

First of all thank you for your work. I tried this on my HP MicroServer Gen10 and I run into following error when I try to build it:

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.msu: 'device_cgroup_rules'`

Does anybody know how to resolve this issue?

**Comment by PJF16** [comment]
Didn't realize that the specified server is still running Ubuntu 18.04 LTS. Therefore the Docker version was too old (didn't support device group rules) and couldn't be upgraded. Upgraded to 22.04 (and updated Docker) and now it works perfectly fine.

**Comment by stegm** [comment]
Thanks for letting me know! 👍
